// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWJrHga5o73BvfSsBGgM4nnRkM7j-luaM',
    appId: '1:858852857854:web:4278181171d451944c12af',
    messagingSenderId: '858852857854',
    projectId: 'chat-pi-6379e',
    authDomain: 'chat-pi-6379e.firebaseapp.com',
    storageBucket: 'chat-pi-6379e.appspot.com',
    measurementId: 'G-QGLCTW5L42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADbBSR7ZaMVRqbrOngHduR2FnTw2oT9aQ',
    appId: '1:858852857854:android:87eaee4360fc4bd54c12af',
    messagingSenderId: '858852857854',
    projectId: 'chat-pi-6379e',
    storageBucket: 'chat-pi-6379e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmNfTkyNA5CU_SF7IosEsi-mqM7uJHdXA',
    appId: '1:858852857854:ios:236c59721c2b51994c12af',
    messagingSenderId: '858852857854',
    projectId: 'chat-pi-6379e',
    storageBucket: 'chat-pi-6379e.appspot.com',
    iosBundleId: 'com.example.chatpi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmNfTkyNA5CU_SF7IosEsi-mqM7uJHdXA',
    appId: '1:858852857854:ios:739cab7941a420564c12af',
    messagingSenderId: '858852857854',
    projectId: 'chat-pi-6379e',
    storageBucket: 'chat-pi-6379e.appspot.com',
    iosBundleId: 'com.example.chatpi.RunnerTests',
  );
}
